CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE TABLE "AttendanceRecords" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StudentName" character varying(200) NOT NULL,
        "ClassName" character varying(50) NOT NULL,
        "Date" date NOT NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE TABLE "StaffMembers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Role" character varying(100) NOT NULL,
        "Department" character varying(100) NOT NULL,
        "Contact" character varying(20) NOT NULL,
        "JoinedOn" date NOT NULL,
        CONSTRAINT "PK_StaffMembers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE TABLE "Students" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "RollNo" character varying(50) NOT NULL,
        "ClassName" character varying(50) NOT NULL,
        "Section" character varying(20) NOT NULL,
        "GuardianName" character varying(200) NOT NULL,
        "Contact" character varying(20) NOT NULL,
        CONSTRAINT "PK_Students" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(320) NOT NULL,
        "PasswordHash" character varying(500) NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE TABLE "FeeRecords" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StudentId" integer NOT NULL,
        "StudentName" character varying(200) NOT NULL,
        "ClassName" character varying(50) NOT NULL,
        "AmountDue" numeric(12,2) NOT NULL,
        "AmountPaid" numeric(12,2) NOT NULL,
        "DueDate" date NOT NULL,
        CONSTRAINT "PK_FeeRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FeeRecords_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE TABLE "PaymentEntries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FeeRecordId" integer NOT NULL,
        "Amount" numeric(12,2) NOT NULL,
        "Date" date NOT NULL,
        "Mode" integer NOT NULL,
        CONSTRAINT "PK_PaymentEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PaymentEntries_FeeRecords_FeeRecordId" FOREIGN KEY ("FeeRecordId") REFERENCES "FeeRecords" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AttendanceRecords_StudentName_Date" ON "AttendanceRecords" ("StudentName", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE INDEX "IX_FeeRecords_StudentId" ON "FeeRecords" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE INDEX "IX_PaymentEntries_FeeRecordId" ON "PaymentEntries" ("FeeRecordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Students_RollNo" ON "Students" ("RollNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725072552_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260725072552_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

