
START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726125646_Master_Tables_Created') THEN
    CREATE TABLE "SchoolClasses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClassName" character varying(50) NOT NULL,
        "Section" character varying(20) NOT NULL,
        CONSTRAINT "PK_SchoolClasses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726125646_Master_Tables_Created') THEN
    CREATE UNIQUE INDEX "IX_SchoolClasses_ClassName_Section" ON "SchoolClasses" ("ClassName", "Section");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726125646_Master_Tables_Created') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260726125646_Master_Tables_Created', '8.0.11');
    END IF;
END $EF$;
COMMIT;

